# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/src
    steps:
      # step 1: obtain repo from Github
      - checkout
      # step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install --no-cache-dir -r requirements.txt
      # step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir test-results
            flake8 --exclude=venv* --statistics
            python -m pytest -v
      # step 4: store test results
      - store_test_results:
          path: test-results/
